# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_manifest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ontent_manifest.proto\"\xef\x02\n\x16\x43ontentManifestPayload\x12\x35\n\x08mappings\x18\x01 \x03(\x0b\x32#.ContentManifestPayload.FileMapping\x1a\x9d\x02\n\x0b\x46ileMapping\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\r\n\x05\x66lags\x18\x03 \x01(\r\x12\x14\n\x0csha_filename\x18\x04 \x01(\x0c\x12\x13\n\x0bsha_content\x18\x05 \x01(\x0c\x12=\n\x06\x63hunks\x18\x06 \x03(\x0b\x32-.ContentManifestPayload.FileMapping.ChunkData\x12\x12\n\nlinktarget\x18\x07 \x01(\t\x1a\x61\n\tChunkData\x12\x0b\n\x03sha\x18\x01 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x02 \x01(\x07\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x13\n\x0b\x63\x62_original\x18\x04 \x01(\r\x12\x15\n\rcb_compressed\x18\x05 \x01(\r\"\xec\x01\n\x17\x43ontentManifestMetadata\x12\x10\n\x08\x64\x65pot_id\x18\x01 \x01(\r\x12\x14\n\x0cgid_manifest\x18\x02 \x01(\x04\x12\x15\n\rcreation_time\x18\x03 \x01(\r\x12\x1b\n\x13\x66ilenames_encrypted\x18\x04 \x01(\x08\x12\x18\n\x10\x63\x62_disk_original\x18\x05 \x01(\x04\x12\x1a\n\x12\x63\x62_disk_compressed\x18\x06 \x01(\x04\x12\x15\n\runique_chunks\x18\x07 \x01(\r\x12\x15\n\rcrc_encrypted\x18\x08 \x01(\r\x12\x11\n\tcrc_clear\x18\t \x01(\r\"-\n\x18\x43ontentManifestSignature\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x42\x02H\x03')



_CONTENTMANIFESTPAYLOAD = DESCRIPTOR.message_types_by_name['ContentManifestPayload']
_CONTENTMANIFESTPAYLOAD_FILEMAPPING = _CONTENTMANIFESTPAYLOAD.nested_types_by_name['FileMapping']
_CONTENTMANIFESTPAYLOAD_FILEMAPPING_CHUNKDATA = _CONTENTMANIFESTPAYLOAD_FILEMAPPING.nested_types_by_name['ChunkData']
_CONTENTMANIFESTMETADATA = DESCRIPTOR.message_types_by_name['ContentManifestMetadata']
_CONTENTMANIFESTSIGNATURE = DESCRIPTOR.message_types_by_name['ContentManifestSignature']
ContentManifestPayload = _reflection.GeneratedProtocolMessageType('ContentManifestPayload', (_message.Message,), {

  'FileMapping' : _reflection.GeneratedProtocolMessageType('FileMapping', (_message.Message,), {

    'ChunkData' : _reflection.GeneratedProtocolMessageType('ChunkData', (_message.Message,), {
      'DESCRIPTOR' : _CONTENTMANIFESTPAYLOAD_FILEMAPPING_CHUNKDATA,
      '__module__' : 'content_manifest_pb2'
      # @@protoc_insertion_point(class_scope:ContentManifestPayload.FileMapping.ChunkData)
      })
    ,
    'DESCRIPTOR' : _CONTENTMANIFESTPAYLOAD_FILEMAPPING,
    '__module__' : 'content_manifest_pb2'
    # @@protoc_insertion_point(class_scope:ContentManifestPayload.FileMapping)
    })
  ,
  'DESCRIPTOR' : _CONTENTMANIFESTPAYLOAD,
  '__module__' : 'content_manifest_pb2'
  # @@protoc_insertion_point(class_scope:ContentManifestPayload)
  })
_sym_db.RegisterMessage(ContentManifestPayload)
_sym_db.RegisterMessage(ContentManifestPayload.FileMapping)
_sym_db.RegisterMessage(ContentManifestPayload.FileMapping.ChunkData)

ContentManifestMetadata = _reflection.GeneratedProtocolMessageType('ContentManifestMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTMANIFESTMETADATA,
  '__module__' : 'content_manifest_pb2'
  # @@protoc_insertion_point(class_scope:ContentManifestMetadata)
  })
_sym_db.RegisterMessage(ContentManifestMetadata)

ContentManifestSignature = _reflection.GeneratedProtocolMessageType('ContentManifestSignature', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTMANIFESTSIGNATURE,
  '__module__' : 'content_manifest_pb2'
  # @@protoc_insertion_point(class_scope:ContentManifestSignature)
  })
_sym_db.RegisterMessage(ContentManifestSignature)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _CONTENTMANIFESTPAYLOAD._serialized_start=27
  _CONTENTMANIFESTPAYLOAD._serialized_end=394
  _CONTENTMANIFESTPAYLOAD_FILEMAPPING._serialized_start=109
  _CONTENTMANIFESTPAYLOAD_FILEMAPPING._serialized_end=394
  _CONTENTMANIFESTPAYLOAD_FILEMAPPING_CHUNKDATA._serialized_start=297
  _CONTENTMANIFESTPAYLOAD_FILEMAPPING_CHUNKDATA._serialized_end=394
  _CONTENTMANIFESTMETADATA._serialized_start=397
  _CONTENTMANIFESTMETADATA._serialized_end=633
  _CONTENTMANIFESTSIGNATURE._serialized_start=635
  _CONTENTMANIFESTSIGNATURE._serialized_end=680
# @@protoc_insertion_point(module_scope)
